###########################################
# canvas.ui.tcl
# Procedure for creating the canvas on
# which drawings will be made
# Iain Ollerenshaw 17/2/98
# Version History:
# Date	Who Comments
# 17/2/98	10	Created
###########################################
# interface generated by SpecTcl version 1.0 from canvas.ui
#	root	is the parent window for this user interface
# This creates a canvas on the window given
# by root
proc canvas_ui {root args} {
    
    # this treats "." as a special case
    if {$root == "."}     {
        set base ""
    } else {
        set base $root
    }
    
    canvas $base.canv \
        -borderwidth 1 \
        -height 500 \
        -relief groove \
        -selectbackground white \
        -width 500 \
        -xscrollincrement 2 \
        -yscrollincrement 2 \
        -yscrollcommand ".test.scrolly set" \
        -xscrollcommand ".test.scrollx set"

    # So our scroll bars work correctly!
    # .test.canv configure -scrollregion
    .test.canv configure -scrollregion {0 0 1000 1000}
    
    bind $base.canv <Button-1> {doClick .test.canv %x %y}
    bind $base.canv <ButtonRelease-1> {doReleaseClick .test.canv %x %y}  
    bind $base.canv <B1-Motion> {doCanvDrag .test.canv %x %y}
    scrollbar $base.scrolly \
    -orient v \
    -command ".test.canv yview"
    
    scrollbar $base.scrollx \
    -orient h \
    -command ".test.canv xview"

    # Geometry management
    grid $base.canv -in $root -row 1 -column 1 -sticky nesw
    grid $base.scrolly -in $root -row 1 -column 2 -sticky nes
    grid $base.scrollx -in $root -row 2 -column 1 -sticky esw
    
    # Resize behavior management
    grid rowconfigure $root 1 -weight 1 -minsize 30
    grid rowconfigure $root 2 -weight 0 -minsize 30
    grid columnconfigure $root 1 -weight 1 -minsize 30
    grid columnconfigure $root 2 -weight 0 -minsize 30

    # additional interface code
    # end additional interface code
}    
# Allow interface to be run "stand-alone" for testing
catch  {
    if [info exists embed_args] {
        # we are running in the plugin
        canvas_ui .
    } else {
        # we are running in stand-alone mode
        if {$argv0 == [info script]} {
            wm title . "Testing about_ui"
            source draw.tcl
            canvas_ui .
        }
    }
}
