###########################################
# menu.ui.tcl
# Code for the creation of the main menu bar
# Iain Ollerenshaw 17/2/98
# Version History:
# Date	Who Comments
# 17/2/98	I0	Created
###########################################
# interface generated by SpecTcl version 1.0 from menu.ui
#	root	is the parent window for this user interface
proc menu_ui {root args} {
    global selectObj
    # this treats "." as a special case
    if {$root == "."} {
        set base ""
        } else {
    set base $root
    }
    
    menubutton $base.fileMenu \
    -menu "$base.fileMenu.m" \
    -text File
    menubutton $base.editMenu \
    -menu "$base.editMenu.m" \
    -text Edit
    menubutton $base.prefsMenu \
    -menu "$base.prefsMenu.m" \
    -text Preferences
    menubutton $base.objectMenu \
    -menu "$base.objectMenu.m" \
    -text Object
    menubutton $base.scriptMenu \
    -menu "$base.scriptMenu.m" \
    -text Script
    menubutton $base.windowMenu \
    -menu "$base.windowMenu.m" \
    -text Window
    menubutton $base.debugMenu \
    -menu "$base.debugMenu.m" \
    -text Debug
    menubutton $base.helpMenu \
    -menu "$base.helpMenu.m" \
    -text Help
    
    # Geometry management
    grid $base.fileMenu -in $root -row 1 -column 1 -sticky nesw
    grid $base.editMenu -in $root -row 1 -column 2 -sticky nesw
    grid $base.prefsMenu -in $root	-row 1 -column 3 -sticky nesw
    grid $base.objectMenu -in $root	-row 1 -column 4 -sticky nesw
    grid $base.scriptMenu -in $root	-row 1 -column 5 -sticky nesw
    grid $base.windowMenu -in $root	-row 1 -column 6 -sticky nesw
    grid $base.debugMenu -in $root	-row 1 -column 7 -sticky nesw
    grid $base.helpMenu -in $root -row 1 -column 9 -sticky nesw

    # Resize behavior management
    grid rowconfigure $root 1 -weight 0 -minsize 2
    grid columnconfigure $root 1 -weight 0 -minsize 30
    grid columnconfigure $root 2 -weight 0 -minsize 30
    grid columnconfigure $root 3 -weight 0 -minsize 30
    grid columnconfigure $root 4 -weight 0 -minsize 30
    grid columnconfigure $root 5 -weight 0 -minsize 30
    grid columnconfigure $root 6 -weight 0 -minsize 30
    grid columnconfigure $root 7 -weight 0 -minsize 30
    grid columnconfigure $root 8 -weight 1 -minsize 30
    grid columnconfigure $root 9 -weight 0 -minsize 30
    
    # additional interface code
    menu $base.fileMenu.m
    $base.fileMenu.m add command -label "Redraw All" -command {doRedraw}
    $base.fileMenu.m add command -label "Do server save" -command {doSave}
    $base.fileMenu.m add command -label "Print" -command {doPrint}
    $base.fileMenu.m add command -label "Quit" -command {doQuit}
    menu $base.editMenu.m
    $base.editMenu.m add command -label "Cut" -command {puts stdout "Cut"}
    $base.editMenu.m add command -label "Copy" -command {puts stdout "Copy"}
    $base.editMenu.m add command -label "Paste" -command {puts stdout "Paste"}
    $base.editMenu.m add command -label "Clear" -command {puts stdout "Clear"}
    menu $base.prefsMenu.m
    $base.prefsMenu.m add command -label "Edit..." -command {doNewPrefs}
    menu $base.scriptMenu.m
    $base.scriptMenu.m add command -label "Execute..." -command {puts stdout "execute"}
    $base.scriptMenu.m add command -label "Create..." -command {puts stdout "create script"}
    menu $base.windowMenu.m
    $base.windowMenu.m add command -label "Untitled" -command {puts stdout "oops!"}
    menu $base.debugMenu.m
    $base.debugMenu.m add command -label "Source" -command {doSource}
    menu $base.helpMenu.m
    $base.helpMenu.m add command -label "About..." -command {doAbout}
    $base.helpMenu.m add command -label "Help..." -command {doHelp}
    menu $base.objectMenu.m
    $base.objectMenu.m add command -label "Create..." -command {puts "create"}
    $base.objectMenu.m add command -label "Delete..." -command {doDelete $selectObj}
    $base.objectMenu.m add command -label "Lock..." -command {doLock $selectObj}
    $base.objectMenu.m add command -label "Commit..." -command {doCommit $selectObj}
    $base.objectMenu.m add command -label "Update..." -command {doObjUpdate $selectObj}
    $base.objectMenu.m add command -label "Rotate..." -command {doRotate $selectObj}
    $base.objectMenu.m add command -label "Scale..." -command {doScale $selectObj}
    # end additional interface code
}

# Allow interface to be run "stand-alone" for testing
catch {
    if {$argv0 == [info script]} {
        wm title . "Testing menu"
        source about.ui.tcl
        source dialog.tcl
        menu_ui .
    }
}
