########################################### # objBox.ui.tcl
# This code displays a box containing info
# on the currently selected object.
# Iain Ollerenshaw 25/2/98
# Version History:
# Date	Who Comments
# 25/2/98	IO	Created
###########################################
# interface generated by SpecTcl version 1.0 from /user.sh/io/mudcode/client/Tcl/objBox.ui
#	root	is the parent window for this user interface
# Create the object box
proc objBox_ui {root args} {
    # this treats "." as a special case
    if {$root == "."} {
        set base ""
    } else {
        set base $root
    }
    
    frame $base.frame#2 \
    -relief raised
    frame $base.frame#1
    frame $base.frame#3 \
    -relief raised
    label $base.label#2 \
    -text Name
    label $base.nameLabel \
    -relief raised
    label $base.label#5 \
    -text Owner
    label $base.ownerLabel \
    -relief raised
    label $base.label#14 \
    -text Layer
    label $base.layerLabel \
    -relief raised
    label $base.label#7 \
    -text {Top Left}
    label $base.tlx1abel \
    -relief raised
    label $base.tly1abel \
    -relief raised
    label $base.label#8 \
    -text {Bot Right}
    label $base.brx1abel \
    -relief raised
    label $base.bry1abel \
    -relief raised
    
    # Geometry management
    grid $base.frame#2 -in $root -row 2 -column 2 -columnspan 2
    grid $base.frame#1 -in $root -row 1 -column 2 -columnspan 2
    grid $base.frame#3 -in $root -row 3 -column 2 -columnspan 2
    grid $base.label#2 -in $root -row 1 -column 1 -sticky nesw
    grid $base.nameLabel -in $base.frame#1	-row 1 -column 1 -sticky nesw
    grid $base.label#5 -in $root -row 2 -column 1 -sticky nesw
    grid $base.ownerLabel -in $base.frame#2	-row 1 -column 1 -sticky nesw
    grid $base.label#14 -in $root -row 3 -column 1 -sticky nesw
    grid $base.layerLabel -in $base.frame#3	-row 1 -column 1 -sticky nesw
    grid $base.label#7 -in $root -row 4 -column 1  -sticky nesw
    grid $base.tlx1abel -in $root -row 4 -column 2 -sticky nesw
    grid $base.tly1abel -in $root -row 4 -column 3 -sticky nesw
    grid $base.label#8 -in $root -row 5 -column 1 -sticky nesw
    grid $base.brx1abel -in $root -row 5 -column 2 -sticky nesw
    grid $base.bry1abel -in $root -row 5 -column 3 -sticky nesw
    
    # Resize behavior management
    grid rowconfigure $base.frame#2 1 -weight 0 -minsize 30
    grid columnconfigure $base.frame#2 1 -weight 0 -minsize 128
    grid rowconfigure $base.frame#3 1 -weight 0 -minsize 30
    grid columnconfigure $base.frame#3 1 -weight 0 -minsize 128
    grid rowconfigure $root 1 -weight 0 -minsize 30
    grid rowconfigure $root 2 -weight 0 -minsize 30
    grid rowconfigure $root 3 -weight 0 -minsize 30
    grid rowconfigure $root 4 -weight 0 -minsize 30
    grid rowconfigure $root 5 -weight 0 -minsize 30
    grid columnconfigure $root 1 -weight 0 -minsize 30
    grid columnconfigure $root 2 -weight 0 -minsize 66
    grid columnconfigure $root 3 -weight 0 -minsize 2
    grid rowconfigure $base.frame#1 1 -weight 0 -minsize 30
    grid columnconfigure $base.frame#1 1 -weight 0 -minsize 127
    
    # additional interface code
    # end additional interface code
}

# Allow interface to be run "stand-alone" for testing
catch {
    if {$argv0 == [info script]} {
        wm title . "Testing objBox"
        objBox_ui .
    }
}
