########################################### # prefs.ui.tcl
# Displays the prefs dialog box and calls
# relevant prefs procs
# Iain Ollerenshaw 5/3/98
# Version History:
# Date	Who Comments
# 5/3/98	IO	Created
###########################################
# interface generated by SpecTcl version 1.0 from prefs.ui
#	root	is the parent window for this user interface
# Display the prefs dialog
proc prefs_ui {root args} {
    global serverName printerName portNum clientId

    # this treats "." as a special case
    if {$root == "."} {
        set base ""
    } else {
        set base $root
    }
    
    frame $base.frame#1
    label $base.label#1 \
    -text {Server IP}
    entry $base.serverEntry \
    -textvariable serverName
    label $base.portLabel \
    -text {Port Number}
    entry $base.portEntry \
    -textvariable portNum
    label $base.label#4 \
    -text Printer
    entry $base.printEntry \
    -cursor {} \
    -textvariable printerName
    label $base.label#5 \
    -text Update
    entry $base.rateEntry \
    -textvariable updateRate
    button $base.button#1 \
    -text Save \
    -command {doSavePrefs; destroy .prefs}
    button $base.button#2 \
    -text Revert
    button $base.button#3 \
    -text Cancel \
    -command {destroy .prefs}
    
    # Geometry management
    grid $base.frame#1 -in $root -row 6 -column 1 -columnspan 2
    grid $base.label#1 -in $root -row 1 -column 1 -sticky nesw
    grid $base.serverEntry -in $root	-row 1 -column 2 -sticky nesw
    grid $base.portLabel -in $root	-row 2 -column 1 -sticky nesw
    grid $base.portEntry -in $root	-row 2 -column 2 -sticky nesw
    grid $base.label#4 -in $root -row 3 -column 1 -sticky nesw
    grid $base.printEntry -in $root	-row 3 -column 2 -sticky nesw
    grid $base.label#5 -in $root -row 4 -column 1 -sticky nesw
    grid $base.rateEntry -in $root	-row 4 -column 2 -sticky nesw
    grid $base.button#1 -in $base.frame#1	-row 1 -column 1 -sticky nesw
    grid $base.button#2 -in $base.frame#1	-row 1 -column 3 -sticky nesw
    grid $base.button#3 -in $base.frame#1	-row 1 -column 4 -sticky nesw
    
    # Resize behavior management
    grid rowconfigure $root 1 -weight 0 -minsize 30
    grid rowconfigure $root 2 -weight 0 -minsize 30
    grid rowconfigure $root 3 -weight 0 -minsize 30
    grid rowconfigure $root 4 -weight 0 -minsize 30
    grid rowconfigure $root 6 -weight 0 -minsize 30
    grid columnconfigure $root 1 -weight 0 -minsize 30
    grid columnconfigure $root 2 -weight 0 -minsize 30
    grid rowconfigure $base.frame#1 1 -weight 0 -minsize 30
    grid columnconfigure $base.frame#1 1 -weight 0 -minsize 50
    grid columnconfigure $base.frame#1 2 -weight 0 -minsize 30
    grid columnconfigure $base.frame#1 3 -weight 0 -minsize 30
    grid columnconfigure $base.frame#1 4 -weight 0 -minsize 30
    
    # additional interface code
    # end additional interface code
}

# Allow interface to be run "stand-alone" for testing
catch {
    if {$argv0 == [info script]} {
        wm title . "Testing prefs"
        prefs_ui .
    }
}
