###########################################
# scale.ui.tcl
# Displays the scale dialog box
# Iain Ollerenshaw 17/2/98
# Version History:	•
# Date	Who Comments
# 17/2/98	IO	Created
###########################################
#	interface generated by SpecTcl version 1.1 from Oli's HD:SHProject:MUD Code:Client:Tcl:scale.ui
#	root	is the parent window for this user interface
# Display the scale dialog box
proc scale_ui {root args} {

    global selectedObj

    # this treats "." as a special case
    if {$root == "."} {
        set base ""
    } else {
        set base $root
    }
    
    label $base.label#1 -text Scale
    label $base.objLabel -text label
    label $base.label#3 -text {X%}
    label $base.label#4 -text {Y%}
    entry $base.scalexEntry -textvariable scalex -width 3
    entry $base.scaleyEntry -textvariable scaley -width 3
    button $base.okayButt -text Okay -command {scale $selectObj $scalex $scaley; destroy .sc}
    button $base.cancelButton -text Cancel -command {destroy .scale}
    
    # Geometry management
    grid $base.label#1 -in $root -row 1 -column 1 -sticky nesw
    grid $base.objLabel -in $root -row 1 -column 2 -sticky nesw
    grid $base.label#3 -in $root -row 2 -column 1 -sticky nesw
    grid $base.scalexEntry -in $root	-row 2 -column 2 -sticky nesw
    grid $base.label#4 -in $root -row 3 -column 1 -sticky nesw
    grid $base.scaleyEntry -in $root	-row 3 -column 2 -sticky nesw
    grid $base.okayButt -in $root -row 4 -column 1 -sticky nesw
    grid $base.cancelButton -in $root -row 4 -column 2 -sticky nesw
    
    # Resize behavior management
    grid rowconfigure $root 1 -weight 0 -minsize 30
    grid rowconfigure $root 2 -weight 0 -minsize 30
    grid rowconfigure $root 3 -weight 0 -minsize 30
    grid rowconfigure $root 4 -weight 0 -minsize 30
    grid columnconfigure $root 1 -weight 0 -minsize 30
    grid columnconfigure $root 2 -weight 0 -minsize 30
    # additional interface code
    # end additional interface code
}
# Allow interface to be run "stand-alone" for testing
catch {
    if [info exists -embed_args] {
        # we are running in the plugin
        scale_ui .
    } else {
        # we are running in stand-alone mode
        if {$argv0 == [info script]} {
            wm title . "Testing scale_ui"
            scale_ui .
        }
    }
}